// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package data

import (
	"context"
)

const bulkLinkCategoriesByName = `-- name: BulkLinkCategoriesByName :exec
INSERT INTO inventory_categories (item_id, category_id)
SELECT $1, id
FROM categories
WHERE name = ANY($2::text[])
`

type BulkLinkCategoriesByNameParams struct {
	ItemID     int32
	Categories []string
}

func (q *Queries) BulkLinkCategoriesByName(ctx context.Context, arg BulkLinkCategoriesByNameParams) error {
	_, err := q.db.Exec(ctx, bulkLinkCategoriesByName, arg.ItemID, arg.Categories)
	return err
}

const deleteItemCategories = `-- name: DeleteItemCategories :exec
DELETE FROM inventory_categories
WHERE item_id = $1
`

func (q *Queries) DeleteItemCategories(ctx context.Context, itemID int32) error {
	_, err := q.db.Exec(ctx, deleteItemCategories, itemID)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT name FROM categories
`

func (q *Queries) GetCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByItemId = `-- name: GetCategoriesByItemId :many
SELECT name FROM categories
LEFT JOIN inventory_categories ON categories.id = inventory_categories.category_id
LEFT JOIN inventory ON inventory_categories.item_id = inventory.id
WHERE inventory.id = $1
`

func (q *Queries) GetCategoriesByItemId(ctx context.Context, itemID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getCategoriesByItemId, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
