// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO inventory (sku, item_name, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, sku, item_name, quantity, price, image_url, created_at, updated_at
`

type CreateItemParams struct {
	Sku      string
	ItemName string
	Quantity int32
	Price    pgtype.Numeric
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Sku,
		arg.ItemName,
		arg.Quantity,
		arg.Price,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.ItemName,
		&i.Quantity,
		&i.Price,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
