// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Inventory struct {
	ID        int32
	Sku       string
	ItemName  string
	Quantity  int32
	Price     pgtype.Numeric
	ImageUrl  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int32
}

type InventoryCategory struct {
	ItemID     int32
	CategoryID int32
}
