// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID        int32
	Sku       string
	ItemName  string
	Quantity  int32
	Price     pgtype.Numeric
	ImageUrl  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
