# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Revive Set up
        uses: morphy2k/revive-action@v2.7.8

      - name: Build
        run: go build -v ./...

      - name: Run Tests & Generate Coverage
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Go Test Coverage Check
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.out
          local-prefix: github.com/${{github.repository}}
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report
          path: coverage.out

      - name: Generate Coverage HTML
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload HTML Visualizer
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html
          path: coverage.html
